// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	ProductCreate(ctx context.Context, arg ProductCreateParams) (*Product, error)
	ProductDelete(ctx context.Context, id int32) error
	ProductGet(ctx context.Context, id int32) (*Product, error)
	ProductUpdateStock(ctx context.Context, arg ProductUpdateStockParams) error
}

var _ Querier = (*Queries)(nil)
