services:
  db:
    image: postgres:15
    container_name: shop_db
    restart: always
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: shop_admin
      POSTGRES_PASSWORD: 2539
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: [ "./main" ]

volumes:
  pgdata:
